version: 2
log-file: "/tmp/efm-langserver.log"
log-level: 3
root-markers:
  - .git/
tools:
  prettier: &prettier
    format-command: "npx --no-install prettier"
languages:
  typescript:
    - <<: *prettier
